name: Build Golang
on: push
jobs:
    run:
        env:
          CONFIG_APIKEY: ${{ secrets.API_KEY }}
          CONFIG_APISECRET: ${{ secrets.API_SECRET }}
        strategy:
          matrix:
            go-version: [ 1.13.x ]
            platform: [ ubuntu-latest ]
        runs-on: ${{ matrix.platform }}
        steps:
            - name: Install Go
              uses: actions/setup-go@v1
              with:
                go-version: ${{ matrix.go-version }}
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Run
              sun: go run main.go