name: poll-bitvavo
on:
  schedule:
    - cron: '*/1 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl 'https://bitvavo.vercel.app/api/buy'